name: Docs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sphinx Publish
        uses: totaldebug/sphinx-publish-action@1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sphinx_src: './docs/source'
